---
resources:
- name: git-resource
  type: git
  source:
    uri: ((git-url))
- name: app-image
  type: pack-image-resource
  source:
    repository: ((repository))
    username: ((docker-hub-username))
    password: ((docker-hub-password))

resource_types:
- name: pack-image-resource
  type: docker-image
  privileged: true
  source:
    repository: ggoksu/pack-concourse-resource
    version: latest

jobs:
- name: build
  plan:
  - get: git-resource
    trigger: true
  - put: app-image
    params:
      build: git-resource
      builder: ((pack-builder))
